#!/bin/bash
MYPATH="${HOME}/bin:${HOME}/emulation/bin:/usr/local/MATLAB/R2013a/bin"
if echo "$PATH" | grep -qv "$MYPATH"; then
	export PATH="${MYPATH}:${PATH}"
fi
export LTMUX="/usr/local/share/ltmux"
export RTMUX="/usr/local/share/rtmux"
